---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: dheeman29/netflix-website:v1
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
  metadata:
    name: spring-boot-app-service
  spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
    selector:
      app: spring-boot-app
